### ISSUE TITLE
Required tag does not work

### ISSUE THREAD

**Issue by muneebaahmad** [MNF/Samples#1]
https://github.com/MNF/Samples/blob/4154168ead5ddeab678a2b444ab12445db124be7/SwashbuckleExample/SwashbuckleExample/Controllers/SwashBuckleTest.cs#L14

**Comment by MNF** [comment]
Yes, it is an example , that required guid  is not working. Please add your considerations to https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/683 to convince the author of importance to change the behaviour
